package com.manishjajoriya.moctale.domain.model.content

import com.google.gson.annotations.SerializedName

data class Content(
    @SerializedName("actor_list") val actorList: List<Actor>,
    @SerializedName("age_rating_formatted") val ageRatingFormatted: String?,
    val banner: String,
    @SerializedName("award_description") val awardDescription: Any?,
    @SerializedName("category_list") val categoryList: List<Category>,
    @SerializedName("count_negative_review") val countNegativeReview: Int,
    @SerializedName("count_neutral_review") val countNeutralReview: Int,
    @SerializedName("count_perfect_review") val countPerfectReview: Int,
    @SerializedName("count_positive_review") val countPositiveReview: Int,
    @SerializedName("count_total_review") val countTotalReview: Int,
    @SerializedName("count_watched") val countWatched: Int,
    @SerializedName("country_of_origin") val countryOfOrigin: CountryOfOrigin,
    @SerializedName("crew_list") val crewList: List<Crew>,
    val description: String,
    @SerializedName("director_list") val directorList: List<Director>,
    @SerializedName("duration_formatted") val durationFormatted: String,
    @SerializedName("editor_choice_note") val editorChoiceNote: Any?,
    @SerializedName("event_list") val eventList: List<Any>,
    @SerializedName("full_image") val fullImage: String,
    @SerializedName("genre_list") val genreList: List<Genre>,
    @SerializedName("has_season_list") val hasSeasonList: Boolean,
    @SerializedName("has_tickets") val hasTickets: Boolean,
    val image: String,
    @SerializedName("is_anime") val isAnime: Boolean,
    @SerializedName("is_award_winner") val isAwardWinner: Boolean,
    @SerializedName("is_editor_choice") val isEditorChoice: Boolean,
    @SerializedName("is_family_friendly") val isFamilyFriendly: Boolean,
    @SerializedName("is_released") val isReleased: Boolean,
    @SerializedName("is_show") val isShow: Boolean,
    @SerializedName("language_list") val languageList: List<Language>,
    val name: String,
    @SerializedName("number_of_seasons") val numberOfSeasons: Int,
    @SerializedName("percent_negative_review") val percentNegativeReview: Double,
    @SerializedName("percent_neutral_review") val percentNeutralReview: Double,
    @SerializedName("percent_perfect_review") val percentPerfectReview: Double,
    @SerializedName("percent_positive_review") val percentPositiveReview: Double,
    @SerializedName("production_house_list") val productionHouseList: List<Any>,
    val slug: String,
    @SerializedName("streaming_site_list") val streamingSiteList: List<Any>,
    @SerializedName("ticketing_site_list") val ticketingSiteList: List<TicketingSite>,
    @SerializedName("video_list") val videoList: List<Video>,
    val year: Int,
    @SerializedName("youtube_review_list") val youtubeReviewList: List<Any>,
)
